// Standalone test for offline orientation RE-FUSION + parity (orientation_refuser.h)
// — the load-bearing capability for post-hoc tuning of the orientation filter
// (docs/validation/pipeline_validation_and_tuning.md §5.3.1; the corpus-1
// pre-collection gate E1, corpus1_collection_protocol.md §0a).
//
// It proves the four properties that make the re-fusion a usable tuning substrate:
//   A. EXACT warm-start reproduction — re-fusing with the production parameters,
//      warm-started from the stored quaternion, reproduces the stored trajectory
//      to float precision. (This is the parity gate run on real pilot swings.)
//   B. PARAMETER SENSITIVITY — changing the filter gain visibly changes the output,
//      so the harness can actually detect the effect of a tuning change.
//   C. WARM-START MATTERS — re-seeding from gravity (cold) loses the pre-window yaw
//      a warm-start preserves, so cold-start diverges where warm-start is exact.
//   D. ESKF FALLBACK — the vendored ESKF cannot be warm-started exactly; the driver
//      reports warmStarted=false and re-fuses without crashing.
//
// Self-contained: the synthetic stream is generated by running the real filter
// forward, so the "stored live quaternion" is exact-by-construction (no recorded
// swing needed). Needs only Eigen (for the ESKF .cpp) — same deps as
// orientation_filter_test.

#include "../../IMU/orientation_filter.h"        // MadgwickFilter (header-only)
#include "../../IMU/eskf_orientation_filter.h"   // EskfOrientationFilter (Eigen-backed)
#include "../../IMU/orientation_refuser.h"       // refuseOrientation / parity

#include <cmath>
#include <cstdio>
#include <vector>

using pinpoint::RefuseSample;
using pinpoint::RefuseConfig;
using pinpoint::refuseOrientation;
using pinpoint::parity;

static int g_fail = 0;

static void check(const char *label, bool ok, const char *detail)
{
    std::printf("  [%s] %-36s %s\n", ok ? "PASS" : "FAIL", label, detail);
    if (!ok) ++g_fail;
}

// --- synthetic motion: constant gyro (yaw accumulates) + a fixed, slightly
//     off-vertical accel so the gravity correction stays active and the gain
//     (beta) genuinely affects the output. Not physical — just deterministic and
//     gain-sensitive, which is all the parity/sensitivity proofs need.
static constexpr float kRate = 200.0f;          // Hz
static constexpr size_t kN   = 600;             // 3 s
static constexpr float  kGx  = 12.0f, kGy = 20.0f, kGz = -18.0f;   // deg/s
static constexpr float  kAx  = 0.10f, kAy = -0.06f, kAz = 0.985f;  // g (off-vertical)
static constexpr float  kD2R = 0.01745329251994329577f;

// Generate the "stored live" trajectory by running MadgwickFilter forward exactly
// as ImuBase::fuseRawImu does on the seed sample (initFromAccel + update) and every
// sample after (update), with nominal dt and gyro converted deg/s -> rad/s.
static std::vector<RefuseSample> genStored(float beta)
{
    std::vector<RefuseSample> s(kN);
    MadgwickFilter f(beta);
    const float dt = 1.0f / kRate;
    for (size_t i = 0; i < kN; ++i) {
        s[i].t_us = int64_t(double(i) * (1.0e6 / kRate));
        s[i].ax = kAx; s[i].ay = kAy; s[i].az = kAz;
        s[i].gx = kGx; s[i].gy = kGy; s[i].gz = kGz;
        if (i == 0)
            f.initFromAccel(kAx, kAy, kAz);
        f.update(kAx, kAy, kAz, kGx * kD2R, kGy * kD2R, kGz * kD2R, dt);
        s[i].qw = f.w(); s[i].qx = f.x(); s[i].qy = f.y(); s[i].qz = f.z();
    }
    return s;
}

int main()
{
    std::printf("=== orientation re-fusion + parity ===\n\n");
    const RefuseConfig warm{ kRate, true };
    const RefuseConfig cold{ kRate, false };
    char buf[160];

    // -- A. Exact warm-start reproduction (the parity gate) --
    std::printf("-- A. warm-start reproduces stored trajectory exactly --\n");
    {
        const auto stored = genStored(0.05f);            // production beta
        MadgwickFilter m(0.05f);
        const auto r = refuseOrientation(m, stored, warm);
        const auto p = parity(stored, r);
        std::snprintf(buf, sizeof buf, "max %.6f deg (mean %.6f, p95 %.6f) over %zu",
                      p.maxDeg, p.meanDeg, p.p95Deg, p.n);
        check("warmStarted flag", r.warmStarted, r.warmStarted ? "true" : "false");
        check("parity max < 1e-2 deg", p.maxDeg < 1e-2, buf);
    }

    // -- B. Parameter sensitivity (the tool can SEE a tuning change) --
    std::printf("\n-- B. a gain change diverges from the stored trajectory --\n");
    {
        const auto stored = genStored(0.05f);            // stored used beta=0.05
        MadgwickFilter m(0.20f);                         // re-fuse with beta=0.20
        const auto r = refuseOrientation(m, stored, warm);
        const auto p = parity(stored, r);
        std::snprintf(buf, sizeof buf, "max %.4f deg (mean %.4f) — must be >0.5", p.maxDeg, p.meanDeg);
        check("gain change is detectable", p.maxDeg > 0.5, buf);
    }

    // -- C. Warm-start matters: cold re-seed loses pre-window yaw --
    std::printf("\n-- C. warm-start preserves pre-window state; cold-seed does not --\n");
    {
        const auto stored = genStored(0.05f);
        const size_t K = 200;                            // a mid-window slice (1 s in)
        const std::vector<RefuseSample> slice(stored.begin() + K, stored.end());

        MadgwickFilter mw(0.05f);
        const auto pw = parity(slice, refuseOrientation(mw, slice, warm));
        MadgwickFilter mc(0.05f);
        const auto pc = parity(slice, refuseOrientation(mc, slice, cold));

        std::snprintf(buf, sizeof buf, "warm max %.6f deg vs cold mean %.4f deg", pw.maxDeg, pc.meanDeg);
        check("warm-start exact on slice", pw.maxDeg < 1e-2, buf);
        check("cold-seed diverges (>1 deg)", pc.meanDeg > 1.0, buf);
        check("warm strictly better than cold", pc.maxDeg > pw.maxDeg, buf);
    }

    // -- D. ESKF cannot be warm-started exactly: graceful fallback, no crash --
    std::printf("\n-- D. ESKF warm-start fallback --\n");
    {
        const auto stored = genStored(0.05f);
        EskfOrientationFilter e;
        const bool settable = e.setOrientation(stored[0].qw, stored[0].qx, stored[0].qy, stored[0].qz);
        check("ESKF setOrientation returns false", settable == false, "vendored lib has no attitude setter");

        EskfOrientationFilter e2;
        const auto r = refuseOrientation(e2, stored, warm);
        std::snprintf(buf, sizeof buf, "warmStarted=%s, produced %zu quats",
                      r.warmStarted ? "true" : "false", r.quat.size());
        check("ESKF re-fuses (fallback, no crash)", !r.warmStarted && r.quat.size() == kN, buf);
    }

    std::printf("\n=== %s (%d failure%s) ===\n", g_fail ? "FAILED" : "PASSED",
                g_fail, g_fail == 1 ? "" : "s");
    return g_fail ? 1 : 0;
}
